baseurl: /documentation
exclude: ['Gemfile', 'Gemfile.lock', 'README.md']
markdown: redcarpet
redcarpet:
  extensions: [tables, no_intra_emphasis, autolink, space_after_headers]
highlighter: pygments
gems:
  - jekyll-sitemap
  - jekyll-redirect-from
sass:
  style: :compressed
  sass_dir: assets/css/_includes

available_locales: ['ja', 'en']
